[book]
authors = ["Ope Bukola", "Folarin Lawal"]
language = "en"
multilingual = false
src = "src"
title = "Project Management and Design"

[build]
build-dir = "output"
create-missing = false
use-default-preprocessors = false
